Repository Ebrisoft/Backend, pull requests merged in 2019-12, with the labels that each got.

#32 Created route for a landlord to get all their houses
  API/Landlord/Controllers/HouseController.cs
  API/Landlord/Endpoints.cs
  API/Landlord/Request/Register.cs
  API/Tenant/Request/Register.cs
  Abstractions/Repositories/IHouseRepository.cs
  SQLServer/Repositories/HouseRepository.cs
Labels: enhancement

#34 Fixed bug; implemented priority to issue response interface and issue…
  API/Landlord/Controllers/FeedController.cs
  API/Landlord/Controllers/IssueController.cs
  API/Landlord/Response/Issue.cs
Labels: bug

#37 Set cookie sameSite mode to none
  API/Startup.cs
Labels: bug, enhancement

#39 Feature/add the ability to close an issue#38
  API/Landlord/Controllers/IssueController.cs
  API/Landlord/Endpoints.cs
  API/Landlord/Request/Archive.cs
  API/Tenant/Controllers/IssueController.cs
  API/Tenant/Endpoints.cs
  API/Tenant/Request/Archive.cs
  Abstractions/Repositories/IIssueRepository.cs
  Abstractions/Repositories/ILandlordRepository.cs
  SQLServer/Repositories/IssueRepository.cs
  SQLServer/Repositories/LandlordRepository.cs
Labels: enhancement
